# apiVersion: skaffold/v2alpha3
apiVersion: skaffold/v2beta24
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  # local:
  #   push: false
  googleCloudBuild:
    projectId: quizlet-330213
  artifacts:
    - image: us.gcr.io/quizlet-330213/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: us.gcr.io/quizlet-330213/client
      context: client
      # hooks:
      #   before:
      #   - command: ["export GOOGLE_APPLICATION_CREDENTIALS='/Users/oliviafelix/Desktop/quizlet-clone/google_creds.json"]
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
