apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: quizlet.dev
      http:
        paths:
          - path: /api/users/?(.*)
            backend:
              serviceName: users-srv
              servicePort: 3000
          - path: /api/sets/?(.*)
            backend:
              serviceName: sets-srv
              servicePort: 3000
          - path: /api/suggestions/?(.*)
            backend:
              serviceName: suggestions-srv
              servicePort: 3000
          - path: /api/folders/?(.*)
            backend:
              serviceName: folders-srv
              servicePort: 3000
          - path: /api/classes/?(.*)
            backend:
              serviceName: classes-srv
              servicePort: 3000
          - path: /api/study/?(.*)
            backend:
              serviceName: study-srv
              servicePort: 3000
          - path: /?(.*)
            backend:
              serviceName: client-srv
              servicePort: 3000