apiVersion: apps/v1
kind: Deployment
metadata:
  name: study-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: study
  template:
    metadata:
      labels:
        app: study
    spec:
      containers:
        - name: study
          image: us.gcr.io/my-quizlet/study
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: quizlet-clone
            - name: MONGO_URI
              value: 'mongodb://study-mongo-srv:27017/study'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: study-srv
spec:
  selector:
    app: study
  ports:
    - name: study
      protocol: TCP
      port: 3000
      targetPort: 3000
